### ISSUE TITLE
Fizzbuzz 구현

### ISSUE THREAD

**Issue by MidasQ** [MidasQ/fizzbuzz-for-me#1]
## Goal
나 홀로 완성해보는 Fizzbuzz

## 요구사항
 - 범위 : 1~20까지의 정수

## Tasks
 - [ ] : Print 'fizz' if i is times of 3.
 - [ ] : Print 'buzz' if i is times of 5.
 - [ ] : Print 'fizzbuzz' if i is times of 15.
 - [ ] : Print i itself for any other cases.
